[workspace]
resolver = "3"
members = ["netem-test", "tests"]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "GPL-2.0-only"

[patch."https://github.com/Banyc/mux.git"]
mux = { path = "../mux" }

[patch."https://github.com/Banyc/rtp.git"]
rtp = { path = "../rtp" }

[patch."https://github.com/Banyc/rtp_mux.git"]
rtp_mux = { path = "../rtp_mux" }

# [patch."https://github.com/Banyc/tokio_udp.git"]
# tokio_udp = { path = "../tokio_udp" }

# [patch."https://github.com/Banyc/udp_listener.git"]
# udp_listener = { path = "../udp_listener" }

[patch."https://github.com/Banyc/dfsql"]
dfsql = { path = "../dfsql" }
