[package]
name = "tests"
edition.workspace = true
version.workspace = true
license.workspace = true

[dev-dependencies]
netem-test = { path = "../netem-test", features = ["test-kit"] }
rtp = { path = "../../rtp", features = ["testing"] }
# rtp = { git = "https://github.com/Banyc/rtp.git", tag = "v0.0.88" }
# mux = { git = "https://github.com/Banyc/mux.git", tag = "v0.0.28" }
mux = { path = "../../mux" }
rtp_mux = { path = "../../rtp_mux" }
tokio = { version = "1", features = ["full", "test-util"] }

[lib]
path = "src/lib.rs"
